### ISSUE TITLE
Duplicate entry errors with mysql storage

### ISSUE THREAD

**Issue by mrcoffee1026** [Nathat23/StackMob-3#208]
started with saying [20:26:35] [Craft Scheduler Thread - 145/WARN]: java.sql.BatchUpdateException: Duplicate entry '00000000-0000-0000-0000-000000000000' for key 'UUID', so I just removed that entry from the DB, but it keeps happening for every key added to the database:

```
[20:24:35] [Craft Scheduler Thread - 126/WARN]: java.sql.BatchUpdateException: Duplicate entry '41f38ad6-4e29-43ac-a229-cf34edcb4676' for key 'UUID'
[20:24:35] [Craft Scheduler Thread - 126/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[20:24:35] [Craft Scheduler Thread - 126/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[20:24:35] [Craft Scheduler Thread - 126/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[20:24:35] [Craft Scheduler Thread - 126/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[20:24:35] [Craft Scheduler Thread - 126/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[20:24:35] [Craft Scheduler Thread - 126/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:408)
[20:24:35] [Craft Scheduler Thread - 126/WARN]: 	at com.mysql.jdbc.SQLError.createBatchUpdateException(SQLError.java:1163)
[20:24:35] [Craft Scheduler Thread - 126/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeBatchedInserts(PreparedStatement.java:1632)
[20:24:35] [Craft Scheduler Thread - 126/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeBatchInternal(PreparedStatement.java:1298)
[20:24:35] [Craft Scheduler Thread - 126/WARN]: 	at com.mysql.jdbc.StatementImpl.executeBatch(StatementImpl.java:970)
[20:24:35] [Craft Scheduler Thread - 126/WARN]: 	at uk.antiperson.stackmob.cache.storage.MySQL.saveStorage(MySQL.java:58)
[20:24:35] [Craft Scheduler Thread - 126/WARN]: 	at uk.antiperson.stackmob.tasks.CacheTask$1.run(CacheTask.java:22)
[20:24:35] [Craft Scheduler Thread - 126/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84)
[20:24:35] [Craft Scheduler Thread - 126/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[20:24:35] [Craft Scheduler Thread - 126/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:24:35] [Craft Scheduler Thread - 126/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[20:24:35] [Craft Scheduler Thread - 126/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[20:24:35] [Craft Scheduler Thread - 126/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[20:24:35] [Craft Scheduler Thread - 126/WARN]: Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '41f38ad6-4e29-43ac-a229-cf34edcb4676' for key 'UUID'
[20:24:35] [Craft Scheduler Thread - 126/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[20:24:35] [Craft Scheduler Thread - 126/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[20:24:35] [Craft Scheduler Thread - 126/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[20:24:35] [Craft Scheduler Thread - 126/WARN]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[20:24:35] [Craft Scheduler Thread - 126/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
[20:24:35] [Craft Scheduler Thread - 126/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:408)
[20:24:35] [Craft Scheduler Thread - 126/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:936)
[20:24:35] [Craft Scheduler Thread - 126/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
[20:24:35] [Craft Scheduler Thread - 126/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
[20:24:35] [Craft Scheduler Thread - 126/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
[20:24:35] [Craft Scheduler Thread - 126/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
[20:24:35] [Craft Scheduler Thread - 126/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495)
[20:24:35] [Craft Scheduler Thread - 126/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903)
[20:24:35] [Craft Scheduler Thread - 126/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2124)
[20:24:35] [Craft Scheduler Thread - 126/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2058)
[20:24:35] [Craft Scheduler Thread - 126/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5158)
[20:24:35] [Craft Scheduler Thread - 126/WARN]: 	at com.mysql.jdbc.PreparedStatement.executeBatchedInserts(PreparedStatement.java:1593)
[20:24:35] [Craft Scheduler Thread - 126/WARN]: 	... 10 more

```

Fairly random with timing but happens pretty regularly.  I'm switching back to flatfile for now though this probably means losing all existing stacks... I don't really have a choice until this is resolved.  Using Stackmob 3.3.5

**Comment by Nathat23** [comment]
Fixed in above commit.
