### ISSUE TITLE
1.14 Not work.

### ISSUE THREAD

**Issue by successed** [Nathat23/StackMob-3#222]
[07:04:20] [Server thread/INFO]: [StackMob] Saving entity amount storage...
[07:04:20] [Server thread/ERROR]: Error occurred while disabling StackMob v3.3.6 (Is it up to date?)
java.lang.NullPointerException: null
	at uk.antiperson.stackmob.StackMob.onDisable(StackMob.java:118) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[spigot-1.14.jar:git-Spigot-1eece4f-d203283]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:377) [spigot-1.14.jar:git-Spigot-1eece4f-d203283]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:437) [spigot-1.14.jar:git-Spigot-1eece4f-d203283]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:429) [spigot-1.14.jar:git-Spigot-1eece4f-d203283]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.disablePlugins(CraftServer.java:392) [spigot-1.14.jar:git-Spigot-1eece4f-d203283]
	at net.minecraft.server.v1_14_R1.MinecraftServer.stop(MinecraftServer.java:676) [spigot-1.14.jar:git-Spigot-1eece4f-d203283]
	at net.minecraft.server.v1_14_R1.DedicatedServer.stop(DedicatedServer.java:695) [spigot-1.14.jar:git-Spigot-1eece4f-d203283]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:842) [spigot-1.14.jar:git-Spigot-1eece4f-d203283]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by Nathat23** [comment]
See #231 for progress on 1.14.
