### ISSUE TITLE
error in console 

### ISSUE THREAD

**Issue by Tarka-Dhal** [Nathat23/StackMob-3#223]
**Describe the bug**
`[01:50:40] [Server thread/WARN]: [StackMob] Task #378 for StackMob v2.2.18 generated an exception
java.lang.IllegalArgumentException: Career id must be greater than 0
	at org.apache.commons.lang.Validate.isTrue(Validate.java:136) ~[patched_1.12.2.jar:git-Paper-1595]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftVillager.getCareer(CraftVillager.java:133) ~[patched_1.12.2.jar:git-Paper-1595]
	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftVillager.getCareer(CraftVillager.java:54) ~[patched_1.12.2.jar:git-Paper-1595]
	at uk.antiperson.stackmob.tools.EntityTools.notMatching(EntityTools.java:76) ~[?:?]
	at uk.antiperson.stackmob.tools.EntityTools.notEnoughNearby(EntityTools.java:344) ~[?:?]
	at uk.antiperson.stackmob.listeners.entity.SpawnEvent$1.run(SpawnEvent.java:93) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1595]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[patched_1.12.2.jar:git-Paper-1595]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[patched_1.12.2.jar:git-Paper-1595]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1595]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1595]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1595]`

**To Reproduce**
On server start.

**Expected behavior**
-

**Screenshots/Videos**
-

**Bukkit/Spigot AND StackMob version:**
StackMob-2.2.18-SNAPSHOT.jar
This server is running Paper version git-Paper-1595 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Additional context**
-

**Comment by Nathat23** [comment]
https://github.com/Nathat23/StackMob-3/issues/109
