### ISSUE TITLE
LoveTrait - Nullpointer

### ISSUE THREAD

**Issue by HgeX** [Nathat23/StackMob-3#224]
Hey! Sometimes I see the following error in the console:

```[21:06:32 WARN]: [StackMob] Task #113 for StackMob v3.3.6 generated an exception
java.lang.NoSuchMethodError: org.bukkit.entity.Animals.isLoveMode()Z
at uk.antiperson.stackmob.checks.trait.LoveTrait.checkTrait(LoveTrait.java:19) ~[?:?]
at uk.antiperson.stackmob.checks.TraitManager.checkTraits(TraitManager.java:38) ~[?:?]
at uk.antiperson.stackmob.entity.EntityTools.notMatching(EntityTools.java:31) ~[?:?]
at uk.antiperson.stackmob.entity.StackLogic.notEnoughNearby(StackLogic.java:86) ~[?:?]
at uk.antiperson.stackmob.tasks.StackTask.run(StackTask.java:29) ~[?:?]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-523]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:git-Paper-523]
at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003) ~[patched_1.13.2.jar:git-Paper-523]
at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-523]
at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-523]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-523]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

To be honest, I don't really know, how to reproduce this, as this error happens rarely, but when it does, the console is spammed with it.

**Spigot version:** Paper 1.13.2 (git-Paper-523)
**Plugin version:** 3.3.6

**Comment by Nathat23** [comment]
You need to update paper, since the method used was only added in the latest versions.

**Comment by HgeX** [comment]
I'll definitely do that, thank you!
