### ISSUE TITLE
Animal won't stack (other mob are fine)

### ISSUE THREAD

**Issue by DeftFury** [Nathat23/StackMob-3#237]
**Describe the bug**
When i try to stack animals it won't work. Every other mobs work just fine.

We want to use this plugin especialy for animal because the maturation of baby animal make the tps drop a lot.

They are not block in the config or other.

We test the same configuration ont a personnal server and everything work fine but on my real server (on paper 523) it won't work.

I use StackMob 4.0.0

**To Reproduce**
Those who seems to not work is every animal that are breedable.

**Expected behavior**
I don't know if you ever seen that before but if you have a solution or maybe know if other plugin/config can cause this probleme it will be apreciated.

Errors:

Here are the errors that i got.

[00:07:22] [Server thread/WARN]: [StackMob] Task #3987 for StackMob v4.0.0 generated an exception
java.lang.NoSuchMethodError: org.bukkit.entity.Animals.isLoveMode()Z
        at uk.antiperson.stackmob.checks.trait.LoveTrait.checkTrait(LoveTrait.java:16) ~[?:?]
        at uk.antiperson.stackmob.checks.TraitManager.checkTraits(TraitManager.java:43) ~[?:?]
        at uk.antiperson.stackmob.entity.EntityTools.notMatching(EntityTools.java:33) ~[?:?]
        at uk.antiperson.stackmob.entity.StackLogic.notEnoughNearby(StackLogic.java:98) ~[?:?]
        at uk.antiperson.stackmob.tasks.SpawnTask.run(SpawnTask.java:35) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-523]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[patched_1.13.2.jar:
git-Paper-523]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003) ~[patched_1.13.2.jar:git-Paper-523]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[patched_1.13.2.jar:git-Paper-523]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[patched_1.13.2.jar:git-Paper-523]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[patched_1.13.2.jar:git-Paper-523]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

**Comment by Nathat23** [comment]
update paper, this will solve the error and the problem you describe.
