### ISSUE TITLE
[StackMob] Task #190 for StackMob v4.0.2 generated an exception

### ISSUE THREAD

**Issue by Dzgs** [Nathat23/StackMob-3#252]
**Describe the bug**
[11:57:59 WARN]: [StackMob] Task #190 for StackMob v4.0.2 generated an exception
java.lang.NoClassDefFoundError: org/apache/commons/lang3/Validate
        at com.comphenix.protocol.injector.netty.ChannelInjector.invokeSendPacket(ChannelInjector.java:651) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.sendServerPacket(ChannelInjector.java:640) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector$4.sendServerPacket(ProtocolInjector.java:403) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:786) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:740) ~[?:?]
        at uk.antiperson.stackmob.compat.hooks.ProtocolLibHook.sendPacket(ProtocolLibHook.java:52) ~[?:?]
        at uk.antiperson.stackmob.tasks.ShowTagTask.run(ShowTagTask.java:50) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.3.jar:git-Paper-124]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.3.jar:git-Paper-124]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1132) ~[patched_1.14.3.jar:git-Paper-124]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.3.jar:git-Paper-124]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1064) ~[patched_1.14.3.jar:git-Paper-124]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.14.3.jar:git-Paper-124]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]

**To Reproduce**
Start the server

**Expected behavior**

**Bukkit/Spigot AND StackMob version:**
Paper 1.14.3 build 124
StackMob v4.0.2

**Comment by Aurelien30000** [comment]
Hey @Dzgs, 
Try to update ProtocolLib to his latest dev version : http://ci.dmulloy2.net/job/ProtocolLib%20Gradle/lastSuccessfulBuild/ :smiley:
