### ISSUE TITLE
Task #11 is creating an error over and over

### ISSUE THREAD

**Issue by Godlycreations** [Nathat23/StackMob-3#268]
**Describe the bug**
I am building a new epicskyblock server and installed your plugin fresh today. to test it out, I created a single stack of mobs and it started showing that error every 3 seconds. This is occurring with any mob stack that is made. To be fully clear, only 5 mobs exist in the world so far.

**To Reproduce**
just stacked 5 sheep

**Expected behavior**
unsure

**Screenshots/Videos**
See below

**Bukkit/Spigot AND StackMob version:**
using papermc1.14.4 and stackmob-4.0.2

**Additional context**
Here is the console posting

22.08 19:02:04 [Server] WARN [StackMob] Task #11 for StackMob v4.0.2 generated an exception
22.08 19:02:04 [Server] INFO java.lang.NoClassDefFoundError: org/apache/commons/lang3/Validate
22.08 19:02:04 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.invokeSendPacket(ChannelInjector.java:651) ~[?:?]
22.08 19:02:04 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.sendServerPacket(ChannelInjector.java:640) ~[?:?]
22.08 19:02:04 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector$4.sendServerPacket(ProtocolInjector.java:403) ~[?:?]
22.08 19:02:04 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:786) ~[?:?]
22.08 19:02:04 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:740) ~[?:?]
22.08 19:02:04 [Server] INFO at uk.antiperson.stackmob.compat.hooks.ProtocolLibHook.sendPacket(ProtocolLibHook.java:52) ~[?:?]
22.08 19:02:04 [Server] INFO at uk.antiperson.stackmob.tasks.ShowTagTask.run(ShowTagTask.java:42) ~[?:?]
22.08 19:02:04 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-175]
22.08 19:02:04 [Server] INFO at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-175]
22.08 19:02:04 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1148) ~[patched_1.14.4.jar:git-Paper-175]
22.08 19:02:04 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-175]
22.08 19:02:04 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1075) ~[patched_1.14.4.jar:git-Paper-175]
22.08 19:02:04 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919) ~[patched_1.14.4.jar:git-Paper-175]
22.08 19:02:04 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by Aurelien30000** [comment]
Try to update ProtocolLib to his latest dev version, designed for 1.14.x :) http://ci.dmulloy2.net/job/ProtocolLib/Gradle/lastSuccessfulBuild/
