### ISSUE TITLE
StackMob generates exception with MythicMobs

### ISSUE THREAD

**Issue by amclay** [Nathat23/StackMob-3#275]
**Describe the bug**
StackMob generates exceptions/warnings when running MythicMobs
```[05:27:47 WARN]: [StackMob] Task #8 for StackMob v4.0.2 generated an exception                                                                                                                                      
java.lang.NoSuchMethodError: 'java.lang.String io.lumine.xikage.mythicmobs.mobs.MythicMob.getDisplayName()'                                                                                                         
        at uk.antiperson.stackmob.compat.hooks.MythicMobsHook.getDisplayName(MythicMobsHook.java:55) ~[?:?]                                                                                                         
        at uk.antiperson.stackmob.tasks.TagTask.run(TagTask.java:48) ~[?:?]                                                                                                                                         
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-192]                                                                                           
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-192]                                                                
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1148) ~[patched_1.14.4.jar:git-Paper-192]                                                                                           
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-192]                                                                                            
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1075) ~[patched_1.14.4.jar:git-Paper-192]                                                                                           
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919) ~[patched_1.14.4.jar:git-Paper-192]                                                                                          
        at java.lang.Thread.run(Thread.java:834) [?:?]                          ```

**To Reproduce**
Install MythicMobs with all examples

**Expected behavior**
no exceptions in logs

**Bukkit/Spigot AND StackMob version:**
Spigot 1.14.4
StackMob v4.0.2

**Comment by amclay** [comment]
closing as dupe of #274
