### ISSUE TITLE
Mobs not stacking

### ISSUE THREAD

**Issue by MrRayhonda** [Nathat23/StackMob-3#283]
**Describe the bug**
Updated from a 4.x version got the bridge, bridge didn't work. Deleted stack mob and bridge and generated files, downloaded latest version 5.x generated files Whitelisted Pig sheep chicken rabbit cow, not stacking. old stacks are still stacked but no mobs will stack. Ver 1.15.1

**To Reproduce**
take sheep egg, spam sheep.

**Expected behavior**
the sheep turn in to a stack of sheep separated by age and color.

**Screenshots/Videos**
https://i.ibb.co/JKPnKvs/2020-01-05-01-10-04.png

**Bukkit/Spigot AND StackMob version:**
Paper 1.15.1 Build#33
StackMob ver 5.0.1

**Additional context**
I think that's about it. I'm completely lost.

**Comment by MrRayhonda** [comment]
error appeared now
16:44:01
[StackMob]: Task #326344 for StackMob v5.0.1 generated an exception
Console 16:44:02
java.lang.UnsupportedOperationException: wait-to-stack.reasons-whitelist list is null!
at uk.antiperson.stackmob.config.ConfigList.contains(ConfigList.java:24) ~[?:?]
at uk.antiperson.stackmob.entity.StackEntity.shouldWait(StackEntity.java:55) ~[?:?]
at uk.antiperson.stackmob.listeners.SpawnListener.lambda$onSpawn$0(SpawnListener.java:29) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.1.jar:git-Paper-33]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.15.1.jar:git-Paper-33]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1179) ~[patched_1.15.1.jar:git-Paper-33]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.15.1.jar:git-Paper-33]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1106) ~[patched_1.15.1.jar:git-Paper-33]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:933) ~[patched_1.15.1.jar:git-Paper-33]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
